// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakip.Data;

#nullable disable

namespace StokTakip.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629142008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("StokTakip.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "İdari İşler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Çevre Odası"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Teknik İşler"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mali Hizmetler"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yazı İşleri"
                        });
                });

            modelBuilder.Entity("StokTakip.Data.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStock")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStock = 50,
                            ItemName = "A4 Kağıt (Koli)",
                            MinimumThreshold = 10
                        },
                        new
                        {
                            Id = 2,
                            CurrentStock = 8,
                            ItemName = "Tükenmez Kalem",
                            MinimumThreshold = 20
                        },
                        new
                        {
                            Id = 3,
                            CurrentStock = 3,
                            ItemName = "Su Şişesi (Damacana)",
                            MinimumThreshold = 5
                        },
                        new
                        {
                            Id = 4,
                            CurrentStock = 25,
                            ItemName = "Zımba Teli",
                            MinimumThreshold = 10
                        },
                        new
                        {
                            Id = 5,
                            CurrentStock = 2,
                            ItemName = "Toner (Siyah)",
                            MinimumThreshold = 3
                        });
                });

            modelBuilder.Entity("StokTakip.Data.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ItemId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("StokTakip.Data.Models.Transaction", b =>
                {
                    b.HasOne("StokTakip.Data.Models.Department", "Department")
                        .WithMany("Transactions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakip.Data.Models.InventoryItem", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StokTakip.Data.Models.Department", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StokTakip.Data.Models.InventoryItem", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
